// <auto-generated>
//  !! WARNING !! This file is auto-generated. Changes to this file will be lost.
// </auto-generated>

using System;

using CashFlow.Enums;
using GraphQL.Conventions;

namespace CashFlow.GraphApi.Schema
{
    [Description("Add an account")]
    [InputType]
    public sealed class AddAccountParameters
    {
        [Description("The name of the account to add")]
        public NonNull<string> Name { get; set; }
        [Description("The type of the account")]
        public AccountType Type { get; set; }
    }

    [Description("Rename an account")]
    [InputType]
    public sealed class RenameAccountParameters
    {
        [Description("The id of the account")]
        public Guid Id { get; set; }
        [Description("The new name of the account")]
        public NonNull<string> Name { get; set; }
    }

    [Description("Change the type of an account")]
    [InputType]
    public sealed class ChangeAccountTypeParameters
    {
        [Description("The id of the account")]
        public Guid Id { get; set; }
        [Description("The new type of the account")]
        public AccountType Type { get; set; }
    }

    [Description("Remove an account")]
    [InputType]
    public sealed class RemoveAccountParameters
    {
        [Description("The id of the account to remove")]
        public Guid Id { get; set; }
    }

    [Description("Add a code")]
    [InputType]
    public sealed class AddCodeParameters
    {
        [Description("The name of the code to add")]
        public NonNull<string> Name { get; set; }
    }

    [Description("Rename a code")]
    [InputType]
    public sealed class RenameCodeParameters
    {
        [Description("The original name of the code")]
        public NonNull<string> OriginalName { get; set; }
        [Description("The new name of the code")]
        public NonNull<string> NewName { get; set; }
    }

    [Description("Remove a code")]
    [InputType]
    public sealed class RemoveCodeParameters
    {
        [Description("The name of the code to remove")]
        public NonNull<string> Name { get; set; }
    }

    [Description("Add a new financial year")]
    [InputType]
    public sealed class AddFinancialYearParameters
    {
        [Description("The name of the new financial year")]
        public NonNull<string> Name { get; set; }
        [Description("The id of the previous financial year")]
        public Guid? PreviousFinancialYearId { get; set; }
    }

    [Description("Set the given financial year as active")]
    [InputType]
    public sealed class ActivateFinancialYearParameters
    {
        [Description("The id of the financial year to activate")]
        public Guid Id { get; set; }
    }

    [Description("Add a supplier")]
    [InputType]
    public sealed class AddSupplierParameters
    {
        [Description("The name of the supplier to add")]
        public NonNull<string> Name { get; set; }
        [Description("The contact info of the supplier")]
        public string ContactInfo { get; set; }
    }

    [Description("Rename a supplier")]
    [InputType]
    public sealed class RenameSupplierParameters
    {
        [Description("The id of the supplier")]
        public Guid Id { get; set; }
        [Description("The new name of the supplier")]
        public NonNull<string> Name { get; set; }
    }

    [Description("Update the contact info of the supplier")]
    [InputType]
    public sealed class UpdateSupplierContactInfoParameters
    {
        [Description("The id of the supplier")]
        public Guid Id { get; set; }
        [Description("The new contact info of the supplier")]
        public string ContactInfo { get; set; }
    }

    [Description("Remove a supplier")]
    [InputType]
    public sealed class RemoveSupplierParameters
    {
        [Description("The id of the supplier to remove")]
        public Guid Id { get; set; }
    }

    [Description("Adds a transaction")]
    [InputType]
    public sealed class AddTransactionParameters
    {
        [Description("The id of the financial year")]
        public Guid FinancialYearId { get; set; }
        [Description("The id of the account related to the transaction")]
        public Guid AccountId { get; set; }
        [Description("The optional id of the supplier linked to the transaction")]
        public Guid? SupplierId { get; set; }
        [Description("The amount. Positive for income, negative for expenses")]
        public decimal Amount { get; set; }
        [Description("True if the transaction is an internal transfer between accounts, false when actual income or expense")]
        public bool IsInternalTransfer { get; set; }
        [Description("The description of the transaction")]
        public NonNull<string> Description { get; set; }
        [Description("Optional comment related to the transaction")]
        public string Comment { get; set; }
        [Description("Zero or more names of codes linked to the transaction")]
        public NonNull<string[]> CodeNames { get; set; }
    }

}
