// <auto-generated>
//  !! WARNING !! This file is auto-generated. Changes to this file will be lost.
// </auto-generated>

using System;

using CashFlow.Enums;

namespace CashFlow.Command.Abstractions
{
    /// <summary>
    /// Add an account
    /// </summary>
    public sealed class AddAccountCommand : Command
    {
        /// <summary>
        /// The id of the account
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The name of the account to add
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// The type of the account
        /// </summary>
        public AccountType Type { get; set; }
    }

    /// <summary>
    /// Rename an account
    /// </summary>
    public sealed class RenameAccountCommand : Command
    {
        /// <summary>
        /// The id of the account
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The new name of the account
        /// </summary>
        public string Name { get; set; }
    }

    /// <summary>
    /// Change the type of an account
    /// </summary>
    public sealed class ChangeAccountTypeCommand : Command
    {
        /// <summary>
        /// The id of the account
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The new type of the account
        /// </summary>
        public AccountType Type { get; set; }
    }

    /// <summary>
    /// Remove an account
    /// </summary>
    public sealed class RemoveAccountCommand : Command
    {
        /// <summary>
        /// The id of the account to remove
        /// </summary>
        public Guid Id { get; set; }
    }

    /// <summary>
    /// Add a code
    /// </summary>
    public sealed class AddCodeCommand : Command
    {
        /// <summary>
        /// The name of the code to add
        /// </summary>
        public string Name { get; set; }
    }

    /// <summary>
    /// Rename a code
    /// </summary>
    public sealed class RenameCodeCommand : Command
    {
        /// <summary>
        /// The original name of the code
        /// </summary>
        public string OriginalName { get; set; }
        /// <summary>
        /// The new name of the code
        /// </summary>
        public string NewName { get; set; }
    }

    /// <summary>
    /// Remove a code
    /// </summary>
    public sealed class RemoveCodeCommand : Command
    {
        /// <summary>
        /// The name of the code to remove
        /// </summary>
        public string Name { get; set; }
    }

    /// <summary>
    /// Add a new financial year
    /// </summary>
    public sealed class AddFinancialYearCommand : Command
    {
        /// <summary>
        /// The id of the new financial year
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The name of the new financial year
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// The id of the previous financial year
        /// </summary>
        public Guid? PreviousFinancialYearId { get; set; }
    }

    /// <summary>
    /// Set the given financial year as active
    /// </summary>
    public sealed class ActivateFinancialYearCommand : Command
    {
        /// <summary>
        /// The id of the financial year to activate
        /// </summary>
        public Guid Id { get; set; }
    }

    /// <summary>
    /// Add a supplier
    /// </summary>
    public sealed class AddSupplierCommand : Command
    {
        /// <summary>
        /// The id of the account
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The name of the supplier to add
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// The contact info of the supplier
        /// </summary>
        public string ContactInfo { get; set; }
    }

    /// <summary>
    /// Rename a supplier
    /// </summary>
    public sealed class RenameSupplierCommand : Command
    {
        /// <summary>
        /// The id of the supplier
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The new name of the supplier
        /// </summary>
        public string Name { get; set; }
    }

    /// <summary>
    /// Update the contact info of the supplier
    /// </summary>
    public sealed class UpdateSupplierContactInfoCommand : Command
    {
        /// <summary>
        /// The id of the supplier
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The new contact info of the supplier
        /// </summary>
        public string ContactInfo { get; set; }
    }

    /// <summary>
    /// Remove a supplier
    /// </summary>
    public sealed class RemoveSupplierCommand : Command
    {
        /// <summary>
        /// The id of the supplier to remove
        /// </summary>
        public Guid Id { get; set; }
    }

    /// <summary>
    /// Adds an income transaction
    /// </summary>
    public sealed class AddIncomeTransactionCommand : Command
    {
        /// <summary>
        /// The id of the transaction
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The id of the financial year
        /// </summary>
        public Guid FinancialYearId { get; set; }
        /// <summary>
        /// The date of the transaction
        /// </summary>
        public DateTimeOffset TransactionDate { get; set; }
        /// <summary>
        /// The id of the account related to the transaction
        /// </summary>
        public Guid AccountId { get; set; }
        /// <summary>
        /// The amount expressed in cents. Positive for income, negative for expenses
        /// </summary>
        public long AmountInCents { get; set; }
        /// <summary>
        /// The description of the transaction
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Optional comment related to the transaction
        /// </summary>
        public string Comment { get; set; }
        /// <summary>
        /// Zero or more names of codes to assign to the transaction
        /// </summary>
        public string[] CodeNames { get; set; }
    }

    /// <summary>
    /// Adds an expense transaction
    /// </summary>
    public sealed class AddExpenseTransactionCommand : Command
    {
        /// <summary>
        /// The id of the transaction
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The id of the financial year
        /// </summary>
        public Guid FinancialYearId { get; set; }
        /// <summary>
        /// The date of the transaction
        /// </summary>
        public DateTimeOffset TransactionDate { get; set; }
        /// <summary>
        /// The id of the account related to the transaction
        /// </summary>
        public Guid AccountId { get; set; }
        /// <summary>
        /// The optional id of the supplier linked to the transaction
        /// </summary>
        public Guid? SupplierId { get; set; }
        /// <summary>
        /// The amount expressed in cents. Positive for income, negative for expenses
        /// </summary>
        public long AmountInCents { get; set; }
        /// <summary>
        /// The description of the transaction
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Optional comment related to the transaction
        /// </summary>
        public string Comment { get; set; }
        /// <summary>
        /// Zero or more names of codes to assign to the transaction
        /// </summary>
        public string[] CodeNames { get; set; }
    }

    /// <summary>
    /// Adds a transfer transaction
    /// </summary>
    public sealed class AddTransferTransactionCommand : Command
    {
        /// <summary>
        /// The id of the origin transaction
        /// </summary>
        public Guid IdOrigin { get; set; }
        /// <summary>
        /// The id of the destination transaction
        /// </summary>
        public Guid IdDestination { get; set; }
        /// <summary>
        /// The id of the financial year
        /// </summary>
        public Guid FinancialYearId { get; set; }
        /// <summary>
        /// The date of the transaction
        /// </summary>
        public DateTimeOffset TransactionDate { get; set; }
        /// <summary>
        /// The id of the origin account related to the transaction
        /// </summary>
        public Guid OriginAccountId { get; set; }
        /// <summary>
        /// The id of the destination account related to the transaction
        /// </summary>
        public Guid DestinationAccountId { get; set; }
        /// <summary>
        /// The amount expressed in cents. Positive for income, negative for expenses
        /// </summary>
        public long AmountInCents { get; set; }
        /// <summary>
        /// The description of the transaction
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Optional comment related to the transaction
        /// </summary>
        public string Comment { get; set; }
        /// <summary>
        /// Zero or more names of codes to assign to the transaction
        /// </summary>
        public string[] CodeNames { get; set; }
    }

    /// <summary>
    /// Removes the latest transaction
    /// </summary>
    public sealed class RemoveLatestTransactionCommand : Command
    {
        /// <summary>
        /// The id of the transaction (used for verification)
        /// </summary>
        public Guid Id { get; set; }
    }

    /// <summary>
    /// Assigns a code to a transaction
    /// </summary>
    public sealed class AssignCodeToTransactionCommand : Command
    {
        /// <summary>
        /// The id of the transaction
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The name of the code to assign
        /// </summary>
        public string CodeName { get; set; }
    }

    /// <summary>
    /// Unassigns a code from a transaction
    /// </summary>
    public sealed class UnassignCodeFromTransactionCommand : Command
    {
        /// <summary>
        /// The id of the transaction
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The name of the code to unassign
        /// </summary>
        public string CodeName { get; set; }
    }

    /// <summary>
    /// Update the description of a transaction
    /// </summary>
    public sealed class UpdateDescriptionOfTransactionCommand : Command
    {
        /// <summary>
        /// The id of the transaction
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The new description of the transaction
        /// </summary>
        public string Description { get; set; }
    }

}
