// <auto-generated>
//  !! WARNING !! This file is auto-generated. Changes to this file will be lost.
// </auto-generated>

using System;

using System.Threading.Tasks;
using AutoMapper;
using CashFlow.Command.Abstractions;
using GraphQL.Conventions;
using MediatR;


namespace CashFlow.GraphApi.Schema
{
#pragma warning disable IDE0008 // Use explicit type
    internal sealed class Mutation
    {
        private readonly IMapper _mapper;

        public Mutation(OutputTypesMapperResolver mapperResolver)
        {
            _mapper = mapperResolver();
        }
    }
#pragma warning restore IDE0008 // Use explicit type
}
